### PR TITLE
Incorporate funding

### PR DESCRIPTION
**Pull request by klimov-paul**
Add GitHub funding flow to facilitate charity donation.

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

**Important** verify the links before merging.

Add any other charity link you know.

### CODE REVIEW

**Comment by iimetra** [comment]
https://uahelp.monobank.ua takes money from cards issued anywhere in the world

**Comment by klimov-paul** [comment]
Added Monobank link.

**Comment by klimov-paul** [comment]
After merging make sure you enable sponsorship at the repository settings.

**Comment by klimov-paul** [comment]
Is the link to PayPal a correct one?

**Comment by iimetra** [comment]
> Is the link to PayPal a correct one?

I trust paypal if it says it is verified link

**Comment by klimov-paul** [comment]
Its done then.

**Pull request merged**
